#!/usr/bin/env python3
"""Regenerate every table and prose number in the synthobj thesis appendix from the package itself.

Run from docs/thesis/ (the Makefile's `tables`/`check` targets do this):

    python regen_tables.py            # write docs/thesis/tables/*.tex
    python regen_tables.py --check    # regenerate into a temp dir and diff against the committed
                                       # tables/*.tex; exit 1 on any difference

This script is the appendix's single source of numerical truth (task-2 brief): every number that
appears in a table, or that a later fragment quotes in prose via a \\SOnum... macro, is computed
here from `synthobj` itself -- never copied from a test file, a docstring or the decision ledger.
It never reads or writes `data/` (a git-ignored build artifact); every objective it needs is built
in-process with `synthobj.make_family`/`synthobj.families.build`.

Structure: one function per table (`TABLE_REGISTRY` below lists them in the brief's order), each
with signature `fn(outdir: Path, stats: dict) -> None`. A function writes its own file under
`outdir` and may stash a number into the shared `stats` dict for a later table (`numbers.tex`) to
read -- `tab_grid_summary` and `tab_quadrature_gap` do this for the two worst-case figures
`numbers.tex` quotes. `get_grid100()` builds the 14 x 10 = 140 objective D=100 study grid once
(memoized at module scope) and every table that needs it shares that one build.
"""
from __future__ import annotations

import argparse
import difflib
import hashlib
import json
import math
import platform
import re
import resource
import subprocess
import sys
import tempfile
import time
from pathlib import Path

import numpy as np
from scipy.optimize import minimize
from scipy.stats import qmc, spearmanr

# --- make `import synthobj` (and `import tests.test_kernel`) work with no PYTHONPATH -----------
REPO_ROOT = Path(__file__).resolve().parent.parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from synthobj import kernel
from synthobj import draws
from synthobj.component import Component
from synthobj.interaction import block_value_and_grad
from synthobj.objective import ACTIVE_EPS, Labels, SyntheticObjective
from synthobj.rotation import EXT_HI, EXT_LO, rotated_block_stats, rotated_block_value_and_grad
from synthobj.families import FAMILIES, ROTATED_GRID_N, STUDY_GRID, build, make_family

from tests.test_kernel import V_REFERENCE

THESIS_DIR = Path(__file__).resolve().parent
TABLES_DIR = THESIS_DIR / "tables"

GENERATED_HEADER = "% generated by regen_tables.py -- do not edit"


# =================================================================================================
# Formatting helpers
# =================================================================================================


def esc(s: str) -> str:
    """Escape a plain Python identifier for LaTeX text/texttt use (our identifiers only ever
    need underscores escaped -- no other LaTeX-special character appears in a variant name, a
    dataclass field name, or a type-annotation string in this codebase)."""
    return s.replace("_", r"\_")


def code(s: str) -> str:
    """`\\SOcode{<escaped s>}`, for a Python identifier (variant name, field name, ...)."""
    return r"\SOcode{" + esc(s) + "}"


def row(cells: list[str]) -> str:
    """One tabular data row: cells joined by ` & `, terminated with ` \\\\`."""
    return " & ".join(cells) + r" \\"


def multicol_note(ncols: int, text: str) -> str:
    return r"\multicolumn{" + str(ncols) + "}{l}{" + text + "}" + r" \\"


def fmt_tuple(values, spec: str = ".2f") -> str:
    return "(" + ", ".join(f"{v:{spec}}" for v in values) + ")"


def fmt_shape(shape) -> str:
    if shape is None:
        return "---"
    if len(shape) == 1:
        return f"({shape[0]},)"
    return "(" + ", ".join(str(s) for s in shape) + ")"


def fmt_signed(x: float, spec: str = ".4f") -> str:
    """`x` formatted to `spec`, with a "-0.0000"-shaped result stripped to "0.0000": a value that
    is zero only to floating-point epsilon (e.g. -2.2e-16) must not render as a *negative* zero,
    which reads as a sign the underlying quantity does not actually have."""
    s = f"{x:{spec}}"
    if s.startswith("-") and float(s) == 0.0:
        s = s[1:]
    return s


def ceil_pow10_label(x: float) -> str:
    """`x`'s magnitude as a power-of-ten ceiling, e.g. 3.2e-16 -> ``$<10^{-15}$``."""
    ax = abs(x)
    if ax == 0.0:
        return "$= 0$"
    e = math.ceil(math.log10(ax))
    return f"$<10^{{{e}}}$"


def macro(name: str, value: str) -> str:
    return r"\newcommand{\SOnum" + name + "}{" + value + "}"


def write_generated(path: Path, extra_header: list[str], body: list[str]) -> None:
    """Write `path` with the standard generated-file header, deterministically."""
    lines = [GENERATED_HEADER, *extra_header, *body]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


# =================================================================================================
# Shared lengthscale sets
# =================================================================================================


def families_ell_set() -> list[float]:
    """Every distinct lengthscale any `FAMILIES` entry uses (its own default spec, D-independent)."""
    ells: set[float] = set()
    for factory in FAMILIES.values():
        spec = factory()
        if isinstance(spec.ells, (int, float)):
            ells.add(float(spec.ells))
        else:
            ells.update(float(e) for e in spec.ells)
    return sorted(ells)


def v_ell_union() -> list[float]:
    """Union of `tests/test_kernel.py`'s `V_REFERENCE` keys with `families_ell_set()`."""
    ells = {float(k) for k in V_REFERENCE.keys()}
    ells.update(families_ell_set())
    return sorted(ells)


# =================================================================================================
# The shared D=100 study grid (14 variants x seeds 0-9), built once
# =================================================================================================

_grid100_cache: dict[tuple[str, int], SyntheticObjective] | None = None
_grid100_build_seconds: float | None = None


def get_grid100() -> dict[tuple[str, int], SyntheticObjective]:
    """The full STUDY_GRID x seeds-0-9 grid at D=100, built once and memoized for this process."""
    global _grid100_cache, _grid100_build_seconds
    if _grid100_cache is None:
        t0 = time.perf_counter()
        cache: dict[tuple[str, int], SyntheticObjective] = {}
        for variant, _family, _overrides in STUDY_GRID:
            for seed in range(10):
                cache[(variant, seed)] = make_family(variant, seed=seed, D=100)
        _grid100_build_seconds = time.perf_counter() - t0
        _grid100_cache = cache
    return _grid100_cache


def paired_coords(obj: SyntheticObjective) -> set[int]:
    """Every coordinate of `obj` that sits in an interaction pair or a rotation pair."""
    coords = {c for inter in obj.interactions for c in (inter.i, inter.j)}
    if obj.rotation is not None:
        coords |= {c for pair in obj.rotation.pairs for c in pair}
    return coords


# =================================================================================================
# Table 1: tab_v_ell.tex
# =================================================================================================


def tab_v_ell(outdir: Path, stats: dict) -> None:
    ells = v_ell_union()
    lines = [
        r"\begin{tabular}{rrrrrr}",
        r"\toprule",
        row([r"$\ell$", r"$\vell{\ell}$", r"$5/(36\ell^2)$", "ratio", r"$5/(3\ell^2\vell{\ell})$", r"$\omega(\ell)$"]),
        r"\midrule",
    ]
    for ell in ells:
        v_val = kernel.v(ell)
        asym = 5.0 / (36.0 * ell**2)
        ratio = v_val / asym
        factor = 5.0 / (3.0 * ell**2 * v_val)
        omega = draws.omega_for_ell(ell)
        lines.append(row([f"{ell:.2f}", f"{v_val:.6f}", f"{asym:.6f}", f"{ratio:.4f}", f"{factor:.4f}", f"{omega:.4f}"]))
    lines += [r"\bottomrule", r"\end{tabular}"]
    write_generated(outdir / "tab_v_ell.tex", [], lines)


# =================================================================================================
# Table 2: tab_families.tex
# =================================================================================================


def tab_families(outdir: Path, stats: dict) -> None:
    lines = [
        r"\begin{tabular}{llrllrrrlcrr}",
        r"\toprule",
        row([
            "variant", "family", r"$|S|$", "shares", r"$\ell$", r"$n_{\text{pairs}}$",
            r"$\gamma$", r"$\theta$", "generator", "monotone", r"$\knots$", code("noise_sd"),
        ]),
        r"\midrule",
    ]
    for variant, family, _overrides in STUDY_GRID:
        obj = make_family(variant, seed=0, D=20)
        spec = obj.spec
        S = list(obj.labels.S)
        n_active = len(S)
        if spec.shares is None:
            # Equal split of (1 - gamma) / |S|; printed as the computed scalar (not the formula
            # string) since all n_active shares are identical here -- reviewer ruling, fix round 1.
            shares_str = f"{float(obj.labels.s[S][0]):.4f}"
        else:
            shares_str = fmt_tuple(spec.shares, ".2f")
        if isinstance(spec.ells, (int, float)):
            ells_str = f"{float(spec.ells):.2f}"
        else:
            ells_str = fmt_tuple(spec.ells, ".2f")
        theta_str = "---" if spec.theta_deg is None else f"{spec.theta_deg:.0f}"
        monotone_str = "yes" if spec.monotone else "no"
        knots = obj.components[0].grid.size
        lines.append(row([
            code(variant), esc(family), str(n_active), shares_str, ells_str, str(spec.n_pairs),
            f"{spec.gamma:.2f}", theta_str, code(spec.generator), monotone_str, str(knots),
            f"{spec.noise_sd:.2f}",
        ]))
    lines += [r"\bottomrule", r"\end{tabular}"]
    write_generated(
        outdir / "tab_families.tex",
        [r"% built at D=20 per variant (family shape is D-invariant; dense_weak's |S| equals D here)"],
        lines,
    )


# =================================================================================================
# Table 3: tab_labels_fields.tex
# =================================================================================================

_LABELS_MEANING: dict[str, tuple[str, str]] = {
    "D": ("scalar", "ambient dimension"),
    "S": (r"$(|S|,)$", "sorted tuple of coordinates carrying a main effect"),
    "active": ("(D,)", "bool mask: membership in S"),
    "s": ("(D,)", "first-order variance share of the pre-rotation main effect (0 off S)"),
    "ell": ("(D,)", "lengthscale of the pre-rotation main effect (NaN off S)"),
    "g": ("(D,)", "realized slope share, normalized over S"),
    "pairs": (r"$(n_{\text{pairs}}, 2)$", "interaction coordinate pairs"),
    "s_pairs": (r"$(n_{\text{pairs}},)$", "interaction shares"),
    "gamma": ("scalar", "total interaction share"),
    "f_star": ("scalar", r"the objective's maximum, $\fstar$"),
    "x_star": ("(D,)", "the maximizer (inactive coordinates at 0.5)"),
    "rotation_deg": ("scalar", r"rotation angle $\theta$ (0 without a rotation)"),
    "rotation_pairs": (r"$(n_{\text{rot}}, 2)$", "rotated coordinate pairs (empty without a rotation)"),
    "s_axis": ("(D,)", "axis-aligned first-order share (equals s without a rotation)"),
    "gamma_axis": ("scalar", "axis-misspecification remainder (equals gamma without a rotation)"),
    "scale": ("scalar", r"global rescale forcing $\Varnu f = 1$ (1 without a rotation)"),
    "generator": ("scalar", r"\SOcode{matern} or \SOcode{sinusoid}"),
    "monotone": ("scalar", "whether the monotone-rejection wrapper was used"),
    "family": ("scalar", r"the study variant name, or \SOcode{custom}"),
    "seed": ("scalar", "the objective's seed"),
    "noise_sd": ("scalar", "observation noise standard deviation"),
    "active_eps": ("scalar", r"the global $\activeeps$ cutoff, recorded for reference"),
}


def tab_labels_fields(outdir: Path, stats: dict) -> None:
    import dataclasses

    field_names = [f.name for f in dataclasses.fields(Labels)]
    have, want = set(field_names), set(_LABELS_MEANING)
    if have != want:
        raise RuntimeError(
            "tab_labels_fields: _LABELS_MEANING is out of sync with dataclasses.fields(Labels): "
            f"missing from dict: {sorted(have - want)}; stale entries in dict: {sorted(want - have)}"
        )

    lines = [
        r"\begin{tabular}{lllp{6.5cm}}",
        r"\toprule",
        row(["field", "type", "shape", "meaning"]),
        r"\midrule",
    ]
    for f in dataclasses.fields(Labels):
        shape, meaning = _LABELS_MEANING[f.name]
        lines.append(row([code(f.name), code(f.type), shape, meaning]))
    lines += [r"\bottomrule", r"\end{tabular}"]
    write_generated(outdir / "tab_labels_fields.tex", [], lines)


# =================================================================================================
# Table 4: tab_npz_json_layout.tex
# =================================================================================================


def tab_npz_json_layout(outdir: Path, stats: dict) -> None:
    with tempfile.TemporaryDirectory(prefix="synthobj_npz_layout_") as tmp:
        tmp_path = Path(tmp)
        obj_a = make_family("interaction_g0.25", seed=0, D=20)
        obj_b = make_family("rotated_t45", seed=0, D=20)
        npz_a, json_a = obj_a.save(tmp_path / "interaction_g0.25")
        npz_b, json_b = obj_b.save(tmp_path / "rotated_t45")

        with np.load(npz_a) as da, np.load(npz_b) as db:
            names = sorted(set(da.files) | set(db.files))
            npz_rows = []
            for name in names:
                arr_a = da[name] if name in da.files else None
                arr_b = db[name] if name in db.files else None
                dtype_str = str(arr_a.dtype if arr_a is not None else arr_b.dtype)
                npz_rows.append((name, fmt_shape(None if arr_a is None else arr_a.shape),
                                  fmt_shape(None if arr_b is None else arr_b.shape), dtype_str))

        payload_a = json.loads(json_a.read_text())
        payload_b = json.loads(json_b.read_text())
        keys = sorted(set(payload_a) | set(payload_b))
        json_rows = []
        for key in keys:
            type_a = type(payload_a[key]).__name__ if key in payload_a else "---"
            type_b = type(payload_b[key]).__name__ if key in payload_b else "---"
            json_rows.append((key, type_a, type_b))

    lines = [
        r"\begin{tabular}{llll}",
        r"\toprule",
        row(["member/key", r"\SOcode{interaction\_g0.25}", r"\SOcode{rotated\_t45}", "dtype"]),
        r"\midrule",
        multicol_note(4, r"\textbf{npz members}"),
    ]
    for name, sa, sb, dt in npz_rows:
        lines.append(row([code(name), sa, sb, esc(dt)]))
    lines.append(r"\midrule")
    lines.append(multicol_note(4, r"\textbf{top-level JSON keys} (Python type of the stored value)"))
    for key, ta, tb in json_rows:
        lines.append(row([code(key), esc(ta), esc(tb), "---"]))
    lines.append(r"\midrule")
    lines.append(multicol_note(
        4,
        r"Note: \SOcode{active}/\SOcode{s}/\SOcode{ell} in the npz are ordered by component "
        r"RANK (build order), one entry per active coordinate -- not by coordinate index the way "
        r"the JSON-side \SOcode{Labels.active}/\SOcode{s}/\SOcode{ell} are (length D, 0/NaN off S).",
    ))
    lines += [r"\bottomrule", r"\end{tabular}"]
    write_generated(outdir / "tab_npz_json_layout.tex", [], lines)


# =================================================================================================
# Table 5: tab_anti_aligned.tex
# =================================================================================================


def tab_anti_aligned(outdir: Path, stats: dict) -> None:
    spec = FAMILIES["anti_aligned"](D=100)
    shares, ells = spec.shares, spec.ells
    n = len(shares)

    raw = [s * 5.0 / (3.0 * ell**2 * kernel.v(ell)) for s, ell in zip(shares, ells)]
    total_raw = sum(raw)
    theoretical = [r / total_raw for r in raw]

    grid100 = get_grid100()
    rank_aligned = []  # one (n,)-vector per seed, g sorted by descending realized s
    for seed in range(10):
        obj = grid100[("anti_aligned", seed)]
        labels = obj.labels
        S = list(labels.S)
        s_S, g_S = labels.s[S], labels.g[S]
        order = np.argsort(-s_S)
        rank_aligned.append(g_S[order])
    mean_g = np.mean(rank_aligned, axis=0)

    rho_theory = spearmanr(theoretical, shares).correlation
    # Two distinct "realized" statistics (reviewer ruling R16, fix round 1): the seed-mean vector
    # correlated against s (n=6), and every individual (seed, rank) realized-g/s pair pooled into
    # one sample (n=60) -- these are materially different numbers (-1.0 vs the pooled figure) and
    # the pooled one is not recoverable from the "mean realized g" data column alone.
    rho_seedmean = spearmanr(mean_g, shares).correlation
    all_g = np.concatenate(rank_aligned)
    all_s = np.tile(shares, len(rank_aligned))
    rho_pooled = spearmanr(all_g, all_s).correlation

    lines = [
        r"\begin{tabular}{rrrrrrr}",
        r"\toprule",
        row(["rank", r"$s_i$", r"$\ell_i$", r"$\vell{\ell_i}$", r"$5/(3\ell_i^2\vell{\ell_i})$",
             "theoretical share", r"mean realized $g$"]),
        r"\midrule",
    ]
    for i in range(n):
        v_i = kernel.v(ells[i])
        factor_i = 5.0 / (3.0 * ells[i] ** 2 * v_i)
        lines.append(row([
            str(i + 1), f"{shares[i]:.2f}", f"{ells[i]:.2f}", f"{v_i:.6f}", f"{factor_i:.4f}",
            f"{theoretical[i]:.4f}", f"{mean_g[i]:.4f}",
        ]))
    lines.append(r"\midrule")
    lines.append(multicol_note(7, f"Spearman(theoretical, $s$) $= {rho_theory:.4f}$"))
    lines.append(multicol_note(
        7, f"Spearman of the seed-mean realized $g$ against $s$ ($n=6$) $= {rho_seedmean:.4f}$"
    ))
    lines.append(multicol_note(
        7, f"Spearman over all sixty (seed, rank) realized pairs ($n=60$) $= {rho_pooled:.4f}$"
    ))
    lines += [r"\bottomrule", r"\end{tabular}"]
    write_generated(outdir / "tab_anti_aligned.tex", [], lines)


# =================================================================================================
# Table 6: tab_decoupled.tex
# =================================================================================================

def _decoupled_cell_name(s: float, ell: float, s_hi: float, ell_lo: float) -> str:
    """"strong"/"weak" from `s` against the spec's own high share; "rough"/"smooth" from `ell`
    against the spec's own low lengthscale -- so a relabeled or rescaled spec still names its
    cells correctly rather than reproducing a hand-typed table."""
    strength = "strong" if s == s_hi else "weak"
    roughness = "rough" if ell == ell_lo else "smooth"
    return f"{strength}-{roughness}"


def tab_decoupled(outdir: Path, stats: dict) -> None:
    spec = FAMILIES["decoupled"](D=100)
    shares, ells = spec.shares, spec.ells
    # Every distinct (s, ell) cell the spec actually uses, in a deterministic sorted order --
    # never a hand-typed list, so a cell added to the spec cannot be silently dropped (reviewer
    # ruling, fix round 1).
    cells = sorted(set(zip(shares, ells)))
    s_hi, ell_lo = max(shares), min(ells)

    # Total theoretical slope energy over all 8 active coordinates (each cell counted with its
    # multiplicity in the spec), so a cell's normalized share matches how Labels.g normalizes.
    total_energy = sum(s * 5.0 / (3.0 * ell**2 * kernel.v(ell)) for s, ell in zip(shares, ells))

    grid100 = get_grid100()
    # `labels.s[coord]`/`labels.ell[coord]` are the exact `spec.shares[rank]`/`spec.ells[rank]`
    # floats `families.build` passed straight through to `Component.from_raw` -- no arithmetic in
    # between -- so exact equality (not a tolerance) is the correct match here, and a coordinate
    # whose (s, ell) is not one of `cells` raises KeyError instead of being silently dropped.
    realized: dict[tuple[float, float], list[float]] = {cell: [] for cell in cells}
    for seed in range(10):
        obj = grid100[("decoupled", seed)]
        labels = obj.labels
        for c in obj.components:
            key = (float(labels.s[c.coord]), float(labels.ell[c.coord]))
            realized[key].append(float(labels.g[c.coord]))

    lines = [
        r"\begin{tabular}{lrrrrr}",
        r"\toprule",
        row(["cell", r"$s$", r"$\ell$", r"$s\cdot 5/(3\ell^2\vell{\ell})$", "theoretical share",
             r"mean realized $g$"]),
        r"\midrule",
    ]
    for s, ell in cells:
        cell_name = _decoupled_cell_name(s, ell, s_hi, ell_lo)
        energy = s * 5.0 / (3.0 * ell**2 * kernel.v(ell))
        share = energy / total_energy
        g_values = realized[(s, ell)]
        mean_g = sum(g_values) / len(g_values)
        lines.append(row([cell_name, f"{s:.2f}", f"{ell:.2f}", f"{energy:.4f}", f"{share:.4f}", f"{mean_g:.4f}"]))
    lines += [r"\bottomrule", r"\end{tabular}"]
    write_generated(outdir / "tab_decoupled.tex", [], lines)


# =================================================================================================
# Table 7: tab_slope_ratio.tex
# =================================================================================================

_SLOPE_RATIO_N = 2000
_SLOPE_RATIO_SEED = 12345
_SLOPE_RATIO_GRID_N = 1024


def tab_slope_ratio(outdir: Path, stats: dict) -> None:
    ells = families_ell_set()
    grid = kernel.make_grid(0.0, 1.0, _SLOPE_RATIO_GRID_N)

    lines = [
        f"% N = {_SLOPE_RATIO_N} draws per ell, default_rng({_SLOPE_RATIO_SEED}) fresh per ell, "
        f"1024-point unit grid; SE = sample std / sqrt(N)",
        r"\begin{tabular}{rrrrr}",
        r"\toprule",
        row([r"$\ell$", r"$5/(3\ell^2\vell{\ell})$", "raw-draw mean $\\pm$ SE", "rescaled mean $\\pm$ SE",
             "ratio (rescaled/theory)"]),
        r"\midrule",
    ]
    for ell in ells:
        F = kernel.eigen_factor(0.0, 1.0, _SLOPE_RATIO_GRID_N, ell)
        rng = np.random.default_rng(_SLOPE_RATIO_SEED)
        theory = 5.0 / (3.0 * ell**2 * kernel.v(ell))
        raw_energies = np.empty(_SLOPE_RATIO_N)
        rescaled_energies = np.empty(_SLOPE_RATIO_N)
        for k in range(_SLOPE_RATIO_N):
            raw_draw = draws.gp_draw(F, rng)
            node_values = raw_draw[-kernel.GL_NODES.size:]
            var_raw = kernel.nu_var(node_values)
            raw_energies[k] = Component.from_raw(0, ell, var_raw, grid, raw_draw, sign=1.0).slope_energy()
            rescaled_energies[k] = Component.from_raw(0, ell, 1.0, grid, raw_draw, sign=1.0).slope_energy()
        raw_mean, raw_se = raw_energies.mean(), raw_energies.std(ddof=1) / math.sqrt(_SLOPE_RATIO_N)
        res_mean, res_se = rescaled_energies.mean(), rescaled_energies.std(ddof=1) / math.sqrt(_SLOPE_RATIO_N)
        ratio = res_mean / theory
        lines.append(row([
            f"{ell:.2f}", f"{theory:.4f}",
            f"{raw_mean:.4f} $\\pm$ {raw_se:.4f}", f"{res_mean:.4f} $\\pm$ {res_se:.4f}", f"{ratio:.4f}",
        ]))
    lines += [r"\bottomrule", r"\end{tabular}"]
    write_generated(outdir / "tab_slope_ratio.tex", [], lines)


# =================================================================================================
# Table 8: tab_quadrature_gap.tex
# =================================================================================================

_QUAD_GAP_N_DRAWS = 20
_QUAD_GAP_SHARE = 0.25
_QUAD_GAP_GRID_N = 1024
_QUAD_GAP_MIDPOINTS = (np.arange(10**6) + 0.5) / 10**6


def tab_quadrature_gap(outdir: Path, stats: dict) -> None:
    ells = families_ell_set()
    grid = kernel.make_grid(0.0, 1.0, _QUAD_GAP_GRID_N)

    lines = [
        r"\begin{tabular}{rrr}",
        r"\toprule",
        row([r"$\ell$", r"$\max|\Enu f_i|$", r"$\max|\Varnu f_i - s|$"]),
        r"\midrule",
    ]
    worst_gap = 0.0
    for ell in ells:
        F = kernel.eigen_factor(0.0, 1.0, _QUAD_GAP_GRID_N, ell)
        max_mean_gap = 0.0
        max_var_gap = 0.0
        for seed in range(_QUAD_GAP_N_DRAWS):
            rng = np.random.default_rng(seed)
            raw_draw = draws.gp_draw(F, rng)
            comp = Component.from_raw(0, ell, _QUAD_GAP_SHARE, grid, raw_draw, sign=1.0)
            values = comp(_QUAD_GAP_MIDPOINTS)
            mid_mean = float(values.mean())
            mid_var = float((values**2).mean() - mid_mean**2)
            max_mean_gap = max(max_mean_gap, abs(mid_mean))
            max_var_gap = max(max_var_gap, abs(mid_var - _QUAD_GAP_SHARE))
        worst_gap = max(worst_gap, max_mean_gap, max_var_gap)
        lines.append(row([f"{ell:.2f}", f"{max_mean_gap:.2e}", f"{max_var_gap:.2e}"]))
    lines += [r"\bottomrule", r"\end{tabular}"]
    write_generated(
        outdir / "tab_quadrature_gap.tex",
        [f"% N = {_QUAD_GAP_N_DRAWS} draws per ell at share={_QUAD_GAP_SHARE}, "
         f"default_rng(seed) for seed in 0..{_QUAD_GAP_N_DRAWS - 1}; "
         "nu-moments by a 10^6-point midpoint rule"],
        lines,
    )
    stats["worst_quad_gap"] = worst_gap


# =================================================================================================
# Table 9: tab_rotation_angle.tex
# =================================================================================================

_ROTATION_ANGLES = [0.0, 15.0, 30.0, 45.0, 60.0, 90.0]
_EXACT_ANGLES = (0.0, 90.0)


def _describe_scale_column(kappa: np.ndarray) -> str:
    """Whether `kappa` (scale) is exactly 1.0 at every seed, or how far it misses -- every number
    here is read off `kappa`, never typed (fix round 2: a hand-typed version of exactly this
    sentence was the bug)."""
    if bool(np.all(kappa == 1.0)):
        return f"exactly 1.0 for all {kappa.size} seeds"
    max_dev = float(np.max(np.abs(kappa - 1.0)))
    return f"not exactly 1.0 at every seed (max $|\\kappa - 1| = {max_dev:.2e}$)"


def _describe_epsilon_column(values: np.ndarray) -> str:
    """How many of `values` are exactly `0.0`, and the actual signed non-zero values (grouped by
    value, formatted `+d.de-dd`) -- again, every number here is read off `values`."""
    n_zero = int(np.sum(values == 0.0))
    nonzero = values[values != 0.0]
    if nonzero.size == 0:
        return f"all {values.size} exactly 0.0"
    unique_vals, counts = np.unique(nonzero, return_counts=True)
    parts = [f"{n_zero} exactly 0.0"] if n_zero else []
    parts += [f"{c} at {v:+.1e}" for v, c in zip(unique_vals, counts)]
    return ", ".join(parts) + f" (of {values.size} seeds)"


def tab_rotation_angle(outdir: Path, stats: dict) -> None:
    grid100 = get_grid100()

    lines = [
        r"\begin{tabular}{rrrrrrrr}",
        r"\toprule",
        row([r"$\theta$", r"$\gaxis$ min", r"$\gaxis$ median", r"$\gaxis$ max", r"$\kappa$ min",
             r"$\kappa$ max", r"count($\kappa>1$)", r"$\max|\mu|$"]),
        r"\midrule",
    ]
    exact_angle_data: dict[float, tuple[np.ndarray, np.ndarray]] = {}
    for theta in _ROTATION_ANGLES:
        objs = []
        for seed in range(10):
            if theta == 0.0:
                objs.append(grid100[("rotated_t0", seed)])
            elif theta == 15.0:
                objs.append(grid100[("rotated_t15", seed)])
            elif theta == 45.0:
                objs.append(grid100[("rotated_t45", seed)])
            else:
                spec = FAMILIES["rotated_t15"](D=100, theta_deg=theta, name=f"rotated_t{int(theta)}")
                objs.append(build(spec, seed))

        gamma_axis = np.array([o.labels.gamma_axis for o in objs])
        kappa = np.array([o.labels.scale for o in objs])
        mu = np.array([o.mu for o in objs])
        if theta in _EXACT_ANGLES:
            exact_angle_data[theta] = (gamma_axis, kappa)
        lines.append(row([
            f"{theta:.0f}",
            fmt_signed(gamma_axis.min()), fmt_signed(float(np.median(gamma_axis))), fmt_signed(gamma_axis.max()),
            f"{kappa.min():.4f}", f"{kappa.max():.4f}",
            str(int(np.sum(kappa > 1.0))),
            f"{np.max(np.abs(mu)):.4f}",
        ]))
    lines += [r"\bottomrule", r"\end{tabular}"]

    # Every number in this note is computed from exact_angle_data just above, not typed: a header
    # comment stating specific per-seed figures must regenerate with the data, not merely quote a
    # measurement taken once and pasted in (fix round 2 -- that was exactly the bug here).
    header = [
        f"% theta={theta:.0f}: kappa (scale) {_describe_scale_column(kappa)};"
        f" gamma_axis {_describe_epsilon_column(gamma_axis)}"
        for theta, (gamma_axis, kappa) in sorted(exact_angle_data.items())
    ]
    header.append(
        "% gamma_axis at theta in {0, 90} is exact only to floating-point epsilon, never a"
        " genuinely negative quantity"
    )
    write_generated(outdir / "tab_rotation_angle.tex", header, lines)


# =================================================================================================
# Table 10: tab_grid_summary.tex
# =================================================================================================


def _qmc_var_mean(obj: SyntheticObjective, D: int, n_points: int, seed: int = 0) -> tuple[float, float]:
    X = qmc.Sobol(d=D, scramble=True, seed=seed).random(n_points)
    f = obj(X)
    return float(np.var(f)), float(np.mean(f))


def tab_grid_summary(outdir: Path, stats: dict) -> None:
    grid100 = get_grid100()

    lines = [
        r"\begin{tabular}{lrlrrr}",
        r"\toprule",
        row(["variant", r"$\knots$", r"$\fstar$ median [min, max]", r"QMC $\Varnu$ min",
             r"QMC $\Varnu$ max", r"$\max|\Enu|$"]),
        r"\midrule",
    ]
    worst_var_dev = 0.0
    worst_mean = 0.0
    for variant, _family, _overrides in STUDY_GRID:
        f_stars = []
        var_hats = []
        mean_hats = []
        knots = None
        for seed in range(10):
            obj = grid100[(variant, seed)]
            if knots is None:
                knots = obj.components[0].grid.size
            f_stars.append(obj.f_star)
            var_hat, mean_hat = _qmc_var_mean(obj, 100, 2**16)
            var_hats.append(var_hat)
            mean_hats.append(mean_hat)
            worst_var_dev = max(worst_var_dev, abs(var_hat - 1.0))
            worst_mean = max(worst_mean, abs(mean_hat))
        f_stars_arr = np.array(f_stars)
        var_arr = np.array(var_hats)
        mean_arr = np.array(mean_hats)
        lines.append(row([
            code(variant), str(knots),
            f"{float(np.median(f_stars_arr)):.4f} [{f_stars_arr.min():.4f}, {f_stars_arr.max():.4f}]",
            f"{var_arr.min():.4f}", f"{var_arr.max():.4f}", f"{np.max(np.abs(mean_arr)):.2e}",
        ]))

    # Extra row: convergence check at 2**20 for rotated_t45 seed 6 alone.
    fine_obj = grid100[("rotated_t45", 6)]
    fine_var, fine_mean = _qmc_var_mean(fine_obj, 100, 2**20)
    knots_fine = fine_obj.components[0].grid.size
    lines.append(r"\midrule")
    lines.append(row([
        code("rotated_t45") + " (seed 6, $N=2^{20}$)", str(knots_fine),
        f"{fine_obj.f_star:.4f} [---, ---]", f"{fine_var:.4f}", f"{fine_var:.4f}", f"{abs(fine_mean):.2e}",
    ]))
    lines += [r"\bottomrule", r"\end{tabular}"]
    write_generated(
        outdir / "tab_grid_summary.tex",
        [r"% Var_nu/E_nu columns are QMC estimates of the TRUE nu-moments -- a fresh"
         r" qmc.Sobol(d=100, scramble=True, seed=0).random(2**16) per objective -- not the"
         r" 64-node nu-hat quadrature (Varhat/Ehat) tab_orthogonality uses"],
        lines,
    )

    stats["worst_var_dev"] = worst_var_dev
    stats["worst_mean"] = worst_mean


# =================================================================================================
# Table 11: tab_orthogonality.tex
# =================================================================================================


def tab_orthogonality(outdir: Path, stats: dict) -> None:
    grid100 = get_grid100()
    GL_NODES, GL_WEIGHTS = kernel.GL_NODES, kernel.GL_WEIGHTS
    w2 = GL_WEIGHTS[:, None] * GL_WEIGHTS[None, :]

    n_blocks = 0
    max_cond = 0.0
    max_orth = 0.0
    max_var = 0.0
    for variant, _family, _overrides in STUDY_GRID:
        if not variant.startswith("interaction_"):
            continue
        for seed in range(10):
            obj = grid100[(variant, seed)]
            by_coord = {c.coord: c for c in obj.components}
            for inter in obj.interactions:
                if inter.c <= 0.0:
                    continue
                n_blocks += 1
                f_i, f_j = by_coord[inter.i], by_coord[inter.j]
                H = inter(GL_NODES[:, None], GL_NODES[None, :])
                e_given_i = H @ GL_WEIGHTS
                e_given_j = GL_WEIGHTS @ H
                max_cond = max(max_cond, float(np.max(np.abs(e_given_i))), float(np.max(np.abs(e_given_j))))
                fi_vals, fj_vals = f_i(GL_NODES), f_j(GL_NODES)
                orth_i = float((w2 * H * fi_vals[:, None]).sum())
                orth_j = float((w2 * H * fj_vals[None, :]).sum())
                max_orth = max(max_orth, abs(orth_i), abs(orth_j))
                # Var_hat h from H/w2 directly (the same 64-node quadrature the row two cells
                # over already computes on), NOT via Interaction.nu_var() -- that method is the
                # algebraic factorization c**2 * Var(u_i) * Var(u_j), i.e. the identity this row
                # claims to check, not an independent measurement of it (reviewer ruling).
                mean_h = float((w2 * H).sum())
                var_h = float((w2 * H**2).sum() - mean_h**2)
                max_var = max(max_var, abs(var_h - inter.c**2))

    lines = [
        r"\begin{tabular}{lrl}",
        r"\toprule",
        row(["quantity", "blocks", "max value"]),
        r"\midrule",
        row([r"$\max |\Ehat[h \mid x_i]|$", str(n_blocks), ceil_pow10_label(max_cond)]),
        row([r"$\max |\Ehat[h f_i]|$", str(n_blocks), ceil_pow10_label(max_orth)]),
        row([r"$\max |\Varhat h - c^2|$", str(n_blocks), ceil_pow10_label(max_var)]),
        r"\bottomrule",
        r"\end{tabular}",
    ]
    write_generated(outdir / "tab_orthogonality.tex", [], lines)


# =================================================================================================
# Table 12: tab_fstar_reopt.tex
# =================================================================================================


def _projected_grad_norm(x: np.ndarray, grad: np.ndarray, lo: float = 0.0, hi: float = 1.0, tol: float = 1e-9) -> float:
    """Max-norm of the bound-projected gradient at `x` (matches L-BFGS-B's own `gtol` criterion):
    a component pointing further out of an active bound is zeroed; every other component (interior,
    or pointing back into the box from a bound) counts in full."""
    proj = np.array(grad, dtype=float)
    for k in range(len(x)):
        at_lower = x[k] <= lo + tol
        at_upper = x[k] >= hi - tol
        if at_lower and grad[k] <= 0.0:
            proj[k] = 0.0
        elif at_upper and grad[k] >= 0.0:
            proj[k] = 0.0
    return float(np.max(np.abs(proj)))


_REOPT_OPTIONS = {"ftol": 1e-18, "gtol": 1e-14, "maxiter": 10000}


def _reopt_stats(block_iter) -> tuple[int, int, float, float]:
    """`block_iter` yields (value_and_grad_fn, x0) pairs; returns
    (n_blocks, n_exact_zero_gain, max_gain, max_projected_grad_norm_at_x0).

    `gain` is `vg_fn(result.x)[0] - value0`: `vg_fn` is called fresh at the point L-BFGS-B
    reports, never `-result.fun` (scipy's own tracked value at that point). The two are not
    always bit-identical -- a block was found where `result.x` is bit-identical to `x0` yet
    `-result.fun` differs from a fresh `vg_fn(result.x)` by a ulp, which is scipy's internal
    bookkeeping, not the objective: several of the module's original "non-zero" gains, all
    computed via `-result.fun`, turned out to be exactly this artifact (reviewer finding, fix
    round 1) -- the exact count is `tab_fstar_reopt.tex`'s own `# exact-zero gain` column, before
    and after this fix, not repeated here. `max_gain` starts at `None` and is set from the first
    computed gain rather than seeded at `0.0`: if every real gain happens to be <= 0 (as here),
    flooring at a literal `0.0` would silently misreport the true (negative) worst case as an
    implausible exact zero.
    """
    n = n_exact_zero = 0
    max_gain: float | None = None
    max_proj = 0.0
    for vg_fn, x0 in block_iter:
        n += 1
        value0, grad0 = vg_fn(x0)
        max_proj = max(max_proj, _projected_grad_norm(x0, grad0))

        def negated(p, vg_fn=vg_fn):
            v, g = vg_fn(p)
            return -v, -g

        result = minimize(negated, x0, jac=True, method="L-BFGS-B",
                           bounds=[(0.0, 1.0), (0.0, 1.0)], options=_REOPT_OPTIONS)
        reopt_value = float(vg_fn(np.asarray(result.x))[0])
        gain = reopt_value - value0
        if gain == 0.0:
            n_exact_zero += 1
        max_gain = gain if max_gain is None else max(max_gain, gain)
    return n, n_exact_zero, max_gain if max_gain is not None else 0.0, max_proj


def _interaction_block_iter(grid100):
    for variant, _family, _overrides in STUDY_GRID:
        for seed in range(10):
            obj = grid100[(variant, seed)]
            by_coord = {c.coord: c for c in obj.components}
            for inter in obj.interactions:
                f_i, f_j = by_coord[inter.i], by_coord[inter.j]
                x0 = np.array([obj.labels.x_star[inter.i], obj.labels.x_star[inter.j]])
                yield (lambda p, f_i=f_i, f_j=f_j, inter=inter: block_value_and_grad(f_i, f_j, inter, p)), x0


def _rotated_block_iter(grid100):
    for variant, _family, _overrides in STUDY_GRID:
        for seed in range(10):
            obj = grid100[(variant, seed)]
            if obj.rotation is None:
                continue
            by_coord = {c.coord: c for c in obj.components}
            for i, j in obj.rotation.pairs:
                f_a, f_b = by_coord[i], by_coord[j]
                x0 = np.array([obj.labels.x_star[i], obj.labels.x_star[j]])
                yield (lambda p, f_a=f_a, f_b=f_b, rot=obj.rotation: rotated_block_value_and_grad(f_a, f_b, rot, p)), x0


def _unpaired_component_gap(grid100) -> tuple[int, float]:
    xs = np.linspace(0.0, 1.0, 10**5)
    n = 0
    max_gap = 0.0
    for variant, _family, _overrides in STUDY_GRID:
        for seed in range(10):
            obj = grid100[(variant, seed)]
            paired = paired_coords(obj)
            for comp in obj.components:
                if comp.coord in paired:
                    continue
                n += 1
                _x_star, f_star_val = comp.argmax()
                grid_max = float(comp(xs).max())
                max_gap = max(max_gap, abs(f_star_val - grid_max))
    return n, max_gap


def tab_fstar_reopt(outdir: Path, stats: dict) -> None:
    grid100 = get_grid100()

    n_i, zero_i, gain_i, proj_i = _reopt_stats(_interaction_block_iter(grid100))
    n_r, zero_r, gain_r, proj_r = _reopt_stats(_rotated_block_iter(grid100))
    n_all, zero_all, gain_all, proj_all = n_i + n_r, zero_i + zero_r, max(gain_i, gain_r), max(proj_i, proj_r)
    n_1d, max_gap_1d = _unpaired_component_gap(grid100)

    lines = [
        r"\begin{tabular}{lrrrr}",
        r"\toprule",
        row(["block type", "count", r"\# exact-zero gain", "max gain", r"max proj.\ grad.\ norm"]),
        r"\midrule",
        row(["interaction blocks", str(n_i), str(zero_i), f"{gain_i:.2e}", f"{proj_i:.2e}"]),
        row(["rotated blocks", str(n_r), str(zero_r), f"{gain_r:.2e}", f"{proj_r:.2e}"]),
        row(["all paired blocks", str(n_all), str(zero_all), f"{gain_all:.2e}", f"{proj_all:.2e}"]),
        r"\midrule",
        row([r"1-D unpaired components ($|f_i(x_i^\star) - \max_{\text{grid}} f_i|$)", str(n_1d), "---", f"{max_gap_1d:.2e}", "---"]),
        r"\bottomrule",
        r"\end{tabular}",
    ]
    write_generated(outdir / "tab_fstar_reopt.tex", [], lines)


# =================================================================================================
# Table 13: numbers.tex
# =================================================================================================


def collect_test_count() -> int:
    result = subprocess.run(
        [sys.executable, "-m", "pytest", "--collect-only", "-q", "tests"],
        cwd=str(REPO_ROOT), capture_output=True, text=True,
    )
    for line in reversed(result.stdout.splitlines()):
        m = re.match(r"(\d+) tests? collected", line.strip())
        if m:
            return int(m.group(1))
    raise RuntimeError(
        "collect_test_count: could not parse a 'N tests collected' line from pytest output:\n"
        f"stdout:\n{result.stdout}\nstderr:\n{result.stderr}"
    )


def numbers_tex(outdir: Path, stats: dict) -> None:
    grid100 = get_grid100()  # already built by now; just ensures the cache-key count below is final

    unit_obj = make_family("aligned3", seed=0, D=20)
    knots_unit = unit_obj.components[0].grid.size
    knots_ext = make_family("rotated_t0", seed=0, D=20).components[0].grid.size

    lines = [
        macro("Next", str(ROTATED_GRID_N)),
        macro("KnotsUnit", str(knots_unit)),
        macro("KnotsExt", str(knots_ext)),
        # Both read off a built objective rather than repeating the literal: StudyD is the D the
        # archived grid is built at, TableD the smaller D tab_families is built at. A2 needs both
        # in prose (dense_weak's share clears ACTIVE_EPS at one and not the other), and reading
        # them back off the objects keeps that prose from drifting if either D ever moves.
        macro("StudyD", str(grid100[("aligned3", 0)].D)),
        macro("TableD", str(unit_obj.D)),
        macro("ZLo", f"{EXT_LO:.4f}"),
        macro("ZHi", f"{EXT_HI:.4f}"),
        macro("ActiveEps", f"{ACTIVE_EPS:.2f}"),
        macro("Variants", str(len(STUDY_GRID))),
        macro("Files", str(len(STUDY_GRID) * 10)),
        macro("CacheKeys", str(len(kernel._eigen_cache))),
        macro("WorstVar", f"{stats['worst_var_dev']:.2e}"),
        macro("WorstMean", f"{stats['worst_mean']:.2e}"),
        macro("WorstQuadGap", f"{stats['worst_quad_gap']:.2e}"),
        macro("TestCount", str(collect_test_count())),
    ]
    write_generated(outdir / "numbers.tex", [], lines)


# =================================================================================================
# Table 14: tab_environment.tex (never diffed by --check)
# =================================================================================================


def _blas_name() -> str:
    try:
        cfg = np.__config__.show(mode="dicts")
        return str(cfg.get("Build Dependencies", {}).get("blas", {}).get("name", "unknown"))
    except Exception:
        return "unknown"


def _peak_rss_mib() -> float:
    ru_maxrss = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
    if platform.system() == "Darwin":
        return ru_maxrss / (1024.0 * 1024.0)  # macOS: bytes
    return ru_maxrss / 1024.0  # Linux: kilobytes


def tab_environment(outdir: Path, stats: dict) -> None:
    grid100 = get_grid100()  # ensure _grid100_build_seconds is set, whichever table built it first
    import scipy

    lines = [
        r"\begin{tabular}{ll}",
        r"\toprule",
        row(["quantity", "value"]),
        r"\midrule",
        row([f"grid build wall time ({len(grid100)} objects, D=100)", f"{_grid100_build_seconds:.2f} s"]),
        row(["peak RSS", f"{_peak_rss_mib():.1f} MiB"]),
        row(["Python", esc(sys.version.split()[0])]),
        row(["numpy", esc(np.__version__)]),
        row(["scipy", esc(scipy.__version__)]),
        row(["platform", esc(platform.platform())]),
        row(["BLAS", esc(_blas_name())]),
        r"\bottomrule",
        r"\end{tabular}",
    ]
    write_generated(outdir / "tab_environment.tex", [], lines)


# =================================================================================================
# Manifest hash-match report (stdout only; never affects a table)
# =================================================================================================


def report_manifest_hash_match(grid100: dict) -> None:
    manifest_path = REPO_ROOT / "data" / "objectives" / "manifest.json"
    if not manifest_path.exists():
        print("data/objectives/manifest.json not found; skipping archived-grid hash check")
        return

    manifest = json.loads(manifest_path.read_text())
    entries = manifest.get("entries", [])
    matched = mismatched = skipped = 0
    with tempfile.TemporaryDirectory(prefix="synthobj_manifest_check_") as tmp:
        tmp_path = Path(tmp)
        for i, entry in enumerate(entries):
            variant, seed, D = entry.get("variant"), entry.get("seed"), entry.get("D")
            if D != 100 or (variant, seed) not in grid100:
                skipped += 1
                continue
            obj = grid100[(variant, seed)]
            npz_path, _json_path = obj.save(tmp_path / f"entry{i:04d}")
            fresh_hash = hashlib.sha256(npz_path.read_bytes()).hexdigest()
            if fresh_hash == entry.get("sha256_npz"):
                matched += 1
            else:
                mismatched += 1
    print(
        f"manifest check: {matched} matched, {mismatched} mismatched, {skipped} skipped "
        f"(of {len(entries)} manifest entries; D=100 entries only)"
    )


# =================================================================================================
# Registry, generation, --check
# =================================================================================================

TABLE_REGISTRY: list[tuple[str, "callable"]] = [
    ("tab_v_ell.tex", tab_v_ell),
    ("tab_families.tex", tab_families),
    ("tab_labels_fields.tex", tab_labels_fields),
    ("tab_npz_json_layout.tex", tab_npz_json_layout),
    ("tab_anti_aligned.tex", tab_anti_aligned),
    ("tab_decoupled.tex", tab_decoupled),
    ("tab_slope_ratio.tex", tab_slope_ratio),
    ("tab_quadrature_gap.tex", tab_quadrature_gap),
    ("tab_rotation_angle.tex", tab_rotation_angle),
    ("tab_grid_summary.tex", tab_grid_summary),
    ("tab_orthogonality.tex", tab_orthogonality),
    ("tab_fstar_reopt.tex", tab_fstar_reopt),
    ("numbers.tex", numbers_tex),
    ("tab_environment.tex", tab_environment),
]


def generate_all(outdir: Path) -> None:
    outdir.mkdir(parents=True, exist_ok=True)
    stats: dict = {}
    total0 = time.perf_counter()
    for filename, fn in TABLE_REGISTRY:
        t0 = time.perf_counter()
        fn(outdir, stats)
        print(f"  {filename}: {time.perf_counter() - t0:.2f}s")
    print(f"regen_tables: {len(TABLE_REGISTRY)} file(s) written to {outdir} in {time.perf_counter() - total0:.2f}s")
    report_manifest_hash_match(get_grid100())


def _diff_files(committed: Path, fresh: Path) -> list[str]:
    a_lines = committed.read_text(encoding="utf-8").splitlines(keepends=True) if committed.exists() else []
    b_lines = fresh.read_text(encoding="utf-8").splitlines(keepends=True) if fresh.exists() else []
    return list(difflib.unified_diff(a_lines, b_lines, fromfile=str(committed), tofile=str(fresh)))


def run_check() -> int:
    diffed_names = [name for name, _fn in TABLE_REGISTRY if name != "tab_environment.tex"]
    with tempfile.TemporaryDirectory(prefix="synthobj_tables_check_") as tmp:
        tmp_path = Path(tmp)
        generate_all(tmp_path)
        mismatches = []
        for name in diffed_names:
            d = _diff_files(TABLES_DIR / name, tmp_path / name)
            if d:
                mismatches.append((name, d))

    if mismatches:
        for name, d in mismatches:
            print(f"=== {name} differs ===")
            sys.stdout.writelines(d)
        print(f"regen_tables --check: {len(mismatches)} of {len(diffed_names)} table(s) differ")
        return 1
    print(f"regen_tables --check: {len(diffed_names)} tables current")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="regenerate into a temp dir and diff")
    args = parser.parse_args(argv)

    if args.check:
        return run_check()
    generate_all(TABLES_DIR)
    return 0


if __name__ == "__main__":
    sys.exit(main())
