#!/usr/bin/env python3
"""Regenerate the R2-D2 prior-family study's thesis tables from an analysis snapshot.

    python regen_study_tables.py                     # write docs/thesis/tables/study_*.tex
    python regen_study_tables.py --check             # regenerate into a temp dir and diff against
                                                     # the committed study_*.tex; exit 1 on any
                                                     # difference
    python regen_study_tables.py --snapshot <dir>    # read <dir>/tables/*.csv instead of
                                                     # sagp_analysis/r2d2/latest

Plan Q9: `regen_tables.py`'s contract is that every number comes from `synthobj` itself, so the
study's tables get this separate script, whose contract is that every number comes from the study's
analysis outputs: the snapshot's `tables/*.csv` (written by its `analyze.py`), stage 0's calibration
table and G0 decision (`sagp_analysis/2026-09-25-r2d2-prior/`), and, for the cost table's
GPU-sharing column, the packed launcher's work lists under `slurm/work/`. No number is typed here.

Each fragment is a whole `table` float whose caption names the snapshot directory it was read from
and the scope it covers (families, seeds and run counts, read from the snapshot's `inventory.csv`),
so a pilot-scope table cannot be mistaken for the final one. Numbers are formatted only; nothing is
re-estimated. The statistic that averages over (family, seed) units is called seed-averaged.

Only numpy-free standard-library code: `csv`, `re`, `pathlib`.
"""
from __future__ import annotations

import argparse
import csv
import difflib
import math
import re
import sys
import tempfile
from pathlib import Path

THESIS_DIR = Path(__file__).resolve().parent
REPO_ROOT = THESIS_DIR.parent.parent
TABLES_DIR = THESIS_DIR / "tables"
DEFAULT_SNAPSHOT = REPO_ROOT / "sagp_analysis" / "r2d2" / "latest"
STAGE0_DIR = REPO_ROOT / "sagp_analysis" / "2026-09-25-r2d2-prior"
WORK_DIR = REPO_ROOT / "slurm" / "work"
PACKED_LAUNCHER = REPO_ROOT / "slurm" / "r2d2_packed.sbatch"

GENERATED_HEADER = "% generated by regen_study_tables.py -- do not edit"

PRIOR_NAMES = {"HC": "half-Cauchy", "R2D2": "R2-D2", "reference": "reference"}


# =================================================================================================
# Reading
# =================================================================================================


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as fh:
        return list(csv.DictReader(fh))


def fnum(s: str) -> float:
    """A CSV cell as a float; an empty cell or 'nan' as NaN."""
    return float(s) if s not in ("", None) else math.nan


class Snapshot:
    """One analysis snapshot: its resolved directory name, its tables, and its scope."""

    def __init__(self, path: Path):
        self.path = path.resolve()
        self.name = self.path.name
        self.tables = self.path / "tables"
        if not self.tables.is_dir():
            raise SystemExit(f"regen_study_tables: no tables/ under {self.path}")
        self.inventory = read_csv(self.tables / "inventory.csv")
        self.summary = read_csv(self.tables / "inventory_summary.csv")
        self.methods = [r["method"] for r in self.summary]  # the analysis's own method order
        regret_files = sorted(self.tables.glob("final_regret_t*.csv"))
        if len(regret_files) != 1:
            raise SystemExit(f"regen_study_tables: expected one final_regret_t*.csv, found {regret_files}")
        self.regret_file = regret_files[0]
        self.t_final = int(re.fullmatch(r"final_regret_t(\d+)\.csv", self.regret_file.name).group(1))

    def csv(self, name: str) -> list[dict[str, str]]:
        return read_csv(self.tables / name)

    def scope(self) -> str:
        """Families, seeds and run counts covered, in words, from inventory.csv/inventory_summary.csv."""
        fam_seeds: dict[str, set[int]] = {}
        for r in self.inventory:
            fam_seeds.setdefault(r["family"], set()).add(int(r["seed"]))
        families = sorted(fam_seeds)
        seed_sets = {frozenset(s) for s in fam_seeds.values()}
        if len(seed_sets) == 1:
            seeds = "seeds " + seed_ranges(next(iter(seed_sets)))
            fam_part = f"{len(families)} famil{'y' if len(families) == 1 else 'ies'} ({join_words([code(f) for f in families])}), {seeds}"
        else:
            fam_part = f"{len(families)} families: " + "; ".join(
                f"{code(f)} seeds {seed_ranges(fam_seeds[f])}" for f in families
            )
        n_runs = sum(int(r["runs"]) for r in self.summary)
        n_complete = sum(int(r["complete"]) for r in self.summary)
        return (
            f"snapshot {code(self.name)} (scope: {fam_part}; {len(self.methods)} methods, "
            f"{n_complete} of {n_runs} runs complete)"
        )


def seed_ranges(seeds) -> str:
    s = sorted(seeds)
    parts, start, prev = [], s[0], s[0]
    for x in s[1:] + [None]:
        if x is not None and x == prev + 1:
            prev = x
            continue
        parts.append(str(start) if start == prev else f"{start}--{prev}")
        if x is not None:
            start = prev = x
    return ", ".join(parts)


def join_words(items: list[str]) -> str:
    if len(items) <= 2:
        return " and ".join(items)
    return ", ".join(items[:-1]) + " and " + items[-1]


# =================================================================================================
# Formatting
# =================================================================================================


def esc(s: str) -> str:
    return s.replace("_", r"\_").replace("%", r"\%")


def code(s: str) -> str:
    return r"\SOcode{" + esc(s) + "}"


def row(cells: list[str]) -> str:
    return " & ".join(cells) + r" \\"


def g3(x: float) -> str:
    """Three significant figures, as the analysis's own .md tables print them; NaN as ---."""
    if math.isnan(x):
        return "---"
    if x != 0 and abs(x) < 1e-3:
        return f"{x:.2e}"
    s = f"{x:.3g}"
    if "e" in s:
        s = f"{x:.0f}"
    if s.startswith("-") and float(s) == 0.0:
        s = s[1:]
    return s


def f3(x: float) -> str:
    """Fixed three decimals, for log10 differences; NaN as ---; no negative zero."""
    if math.isnan(x):
        return "---"
    s = f"{x:.3f}"
    if s.startswith("-") and float(s) == 0.0:
        s = s[1:]
    return s


def interval(lo: float, hi: float, fmt=f3) -> str:
    return f"[{fmt(lo)}, {fmt(hi)}]"


def method_cell(method: str) -> str:
    """A cell as its structure and parameterization initials (`additive-lengthscale_r2d2` -> AL);
    a reference method by its own name. The prior family is shown beside it, never in the label."""
    if "-" not in method:
        return code(method)
    structure, parameterization = method.split("-", 1)
    return (structure[0] + parameterization[0]).upper()


CELL_NAMING = ("Cells are named by two initials, structure then parameterization: A or P for "
               "additive or product, then A or L for amplitude or lengthscale.")


def hd(*lines: str) -> str:
    """A column heading stacked over several lines, so a wide table fits the text block."""
    return lines[0] if len(lines) == 1 else r"\shortstack{" + r"\\ ".join(lines) + "}"


def write_table(path: Path, comment: list[str], caption: str, label: str, body: list[str],
                size: str = r"\scriptsize", sep: str = "3pt") -> None:
    lines = [GENERATED_HEADER, *(f"% {c}" for c in comment),
             r"\begin{table}[tbp]", r"\centering",
             r"\caption{" + caption + r"}\label{" + label + "}",
             size + r"\setlength{\tabcolsep}{" + sep + "}",
             *body, r"\end{table}"]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def interval_levels(header: list[str]) -> list[int]:
    """The interval levels the CSV carries, read off its lo<level> columns (e.g. [90, 95])."""
    return sorted(int(m.group(1)) for h in header if (m := re.fullmatch(r"lo(\d+)", h)))


# =================================================================================================
# 1. Final regret by method and objective family
# =================================================================================================


def study_final_regret(snap: Snapshot, outdir: Path) -> None:
    rows = read_csv(snap.regret_file)
    families = sorted({r["family"] for r in rows})
    by = {(r["family"], r["method"]): r for r in rows}
    prior = {r["method"]: r["prior_family"] for r in rows}
    n_per = sorted({int(r["n"]) for r in rows})
    groups: list[tuple[str, list[str]]] = []  # (prior family, its methods), the analysis's order
    for m in snap.methods:
        if groups and groups[-1][0] == prior[m]:
            groups[-1][1].append(m)
        else:
            groups.append((prior[m], [m]))
    cols = "l" + "".join("r" * len(ms) for _p, ms in groups)
    group_row, rules, c0 = ["objective"], [], 2
    for p, ms in groups:
        group_row.append(r"\multicolumn{" + str(len(ms)) + "}{c}{" + PRIOR_NAMES[p] + "}")
        rules.append(r"\cmidrule(lr){" + f"{c0}-{c0 + len(ms) - 1}" + "}")
        c0 += len(ms)
    body = [r"\begin{tabular}{" + cols + "}", r"\toprule", row(group_row), "".join(rules),
            row(["family", *[method_cell(m) for m in snap.methods]]), r"\midrule"]
    for f in families:
        cells = []
        for m in snap.methods:
            r = by.get((f, m))
            if r is None:
                cells.append("---")
            elif r["rank_in_family"] == "1":
                cells.append(r"\textbf{" + g3(fnum(r["median"])) + "}")
            else:
                cells.append(g3(fnum(r["median"])))
        body.append(row([code(f), *cells]))
    body += [r"\bottomrule", r"\end{tabular}"]
    caption = (
        f"Final simple regret at iteration {snap.t_final} by method and objective family: the median "
        f"over seeds ({join_words([str(n) for n in n_per])} per entry), the lowest in each family in "
        f"bold. {CELL_NAMING} "
        f"The quartiles, the ranks within family and the mean rank within seed are in the snapshot's "
        f"{code(snap.regret_file.name)}. Read from {snap.scope()}."
    )
    write_table(outdir / "study_final_regret.tex", [f"source: {snap.regret_file.name}"],
                caption, "app:so:study:tab:regret", body, sep="1.5pt")


# =================================================================================================
# 2. The two main effects by prior family, their differences, and the intervals
# =================================================================================================

_EFFECT_ROWS = [  # (effect id in effects_pooled.csv, effect label, prior family label)
    ("S_HC", "structure", "half-Cauchy"),
    ("S_R2D2", "structure", "R2-D2"),
    ("dS", "structure", "difference"),
    ("P_HC", "parameterization", "half-Cauchy"),
    ("P_R2D2", "parameterization", "R2-D2"),
    ("dP", "parameterization", "difference"),
]


def study_effects(snap: Snapshot, outdir: Path) -> None:
    path = snap.tables / "effects_pooled.csv"
    rows = read_csv(path)
    header = list(rows[0].keys())
    levels = interval_levels(header)
    by = {r["effect"]: r for r in rows}
    body = [r"\begin{tabular}{llrr" + "c" * len(levels) + "l}", r"\toprule",
            row(["effect", hd("prior", "family"), "median", hd("seed-", "averaged"),
                 *[hd(f"{lv}\\%", "interval") for lv in levels], hd("PR2", "reading")]), r"\midrule"]
    for i, (eid, eff, fam) in enumerate(_EFFECT_ROWS):
        if i == 3:
            body.append(r"\midrule")
        r = by[eid]
        body.append(row([eff, fam, f3(fnum(r["median"])), f3(fnum(r["mean"])),
                         *[interval(fnum(r[f"lo{lv}"]), fnum(r[f"hi{lv}"])) for lv in levels],
                         r["pr2_reading"] or "---"]))
    body += [r"\bottomrule", r"\end{tabular}"]
    n_boot = sorted({r["n_boot"] for r in rows})
    n_units = sorted({by[eid]["n_units"] for eid, _e, _f in _EFFECT_ROWS})
    caption = (
        f"The two main effects on the base-10 logarithm of final regret at iteration {snap.t_final}, "
        f"by prior family, and their differences (R2-D2 minus half-Cauchy). Structure is additive "
        f"minus product and parameterization is amplitude minus lengthscale, each averaged over the "
        f"other factor within one (family, seed) unit; negative means lower regret for additive, or "
        f"for amplitude. Median and seed-averaged value over the {join_words(n_units)} units; the intervals are percentile "
        f"intervals of the seed-averaged value from a (family, seed)-cluster bootstrap with "
        f"{join_words(n_boot)} resamples. The PR2 reading compares the {levels[0]}\\% interval of each "
        f"difference with the preregistered equivalence band. Read from {snap.scope()}."
    )
    write_table(outdir / "study_effects.tex", [f"source: {path.name} (main_HC, main_R2D2, interaction rows)"],
                caption, "app:so:study:tab:effects", body)


# =================================================================================================
# 3. The twin pairs, Delta_c per cell
# =================================================================================================


def study_twins(snap: Snapshot, outdir: Path) -> None:
    pooled_path = snap.tables / "effects_pooled.csv"
    fam_path = snap.tables / "pr3_twin_medians.csv"
    pooled = [r for r in read_csv(pooled_path) if r["kind"] == "twin"]
    levels = interval_levels(list(pooled[0].keys()))
    per_fam = read_csv(fam_path)
    families = sorted({r["family"] for r in per_fam})
    pf = {(r["family"], r["effect"]): r for r in per_fam}
    cells = [m for m in snap.methods if f"Delta_{m}" in {r["effect"] for r in pooled}]
    by = {r["effect"]: r for r in pooled}
    body = [r"\begin{tabular}{lrrr" + "c" * len(levels) + "}", r"\toprule",
            row(["R2-D2 cell", "units", "median", hd("seed-", "averaged"),
                 *[hd(f"{lv}\\%", "interval") for lv in levels]]),
            r"\midrule"]
    for m in cells:
        r = by[f"Delta_{m}"]
        body.append(row([method_cell(m), r["n_units"], f3(fnum(r["median"])), f3(fnum(r["mean"])),
                         *[interval(fnum(r[f"lo{lv}"]), fnum(r[f"hi{lv}"])) for lv in levels]]))
    body += [r"\bottomrule", r"\end{tabular}", r"\par\medskip",
             r"\begin{tabular}{l" + "r" * len(cells) + "}", r"\toprule",
             row(["family", *[method_cell(m) for m in cells]]), r"\midrule"]
    any_fail = False
    for f in families:
        fam_cells = []
        for m in cells:
            q = pf.get((f, f"Delta_{m}"))
            if q is None:
                fam_cells.append("---")
                continue
            mark = "" if q["holds"] == "True" else "*"
            any_fail |= bool(mark)
            fam_cells.append(f3(fnum(q["median"])) + mark)
        body.append(row([code(f), *fam_cells]))
    body += [r"\bottomrule", r"\end{tabular}"]
    n_per = sorted({r["n"] for r in per_fam})
    caption = (
        f"Twin pairs: the difference in the base-10 logarithm of final regret at iteration "
        f"{snap.t_final}, each R2-D2 cell minus its half-Cauchy twin on the same (family, seed); "
        f"positive means higher regret under R2-D2. Upper block, over all units: median, "
        f"seed-averaged value and its (family, seed)-cluster bootstrap percentile intervals. Lower "
        f"block, per family: the median over that family's seeds ({join_words(n_per)} pairs each, "
        f"{code(fam_path.name)})"
        + ("; an asterisk marks a cell and family where the PR3 null does not hold." if any_fail
           else "; the PR3 null holds in every cell and family.")
        + f" {CELL_NAMING} Read from {snap.scope()}."
    )
    write_table(outdir / "study_twins.tex", [f"source: {pooled_path.name} (twin rows), {fam_path.name}"],
                caption, "app:so:study:tab:twins", body)


# =================================================================================================
# 4. Identification by prior family
# =================================================================================================


def study_identification(snap: Snapshot, outdir: Path) -> None:
    path = snap.tables / "identification_by_prior_family.csv"
    pr4_path = snap.tables / "pr4_identification_twin_pairs.csv"
    rows = read_csv(path)
    pr4 = read_csv(pr4_path)
    levels = interval_levels(list(pr4[0].keys()))
    body = [r"\begin{tabular}{llrrrrrrr}", r"\toprule",
            row(["cell", "prior", "runs", hd("AP native", "mean"),
                 hd("AP native", "median"), hd("AP Sobol", "mean"), hd("AP Sobol", "median"),
                 hd("F1", "mean"), hd("predicted", "active", "(median)")]), r"\midrule"]
    prev = None
    for r in rows:
        key = (r["structure"], r["parameterization"])
        if prev is not None and key != prev:
            body.append(r"\addlinespace")
        prev = key
        body.append(row([method_cell(f"{r['structure']}-{r['parameterization']}"), PRIOR_NAMES[r["prior_family"]],
                         r["n_runs"], f3(fnum(r["ap_native_mean"])), f3(fnum(r["ap_native_median"])),
                         f3(fnum(r["ap_sobol_mean"])), f3(fnum(r["ap_sobol_median"])),
                         f3(fnum(r["f1_mean"])), g3(fnum(r["n_pred_active_median"]))]))
    body += [r"\bottomrule", r"\end{tabular}", r"\par\medskip",
             r"\begin{tabular}{llrrr" + "c" * len(levels) + "l}", r"\toprule",
             row(["R2-D2 cell", "metric", "pairs", hd("mean", "difference"), hd("median", "difference"),
                  *[hd(f"{lv}\\%", "interval") for lv in levels], hd("PR4", "reading")]), r"\midrule"]
    for r in pr4:
        metric = {"ap_native": "AP native", "ap_sobol": "AP Sobol"}.get(r["metric"], esc(r["metric"]))
        body.append(row([method_cell(r["cell"]), metric, r["n_pairs"], f3(fnum(r["mean_diff"])),
                         f3(fnum(r["median_diff"])),
                         *[interval(fnum(r[f"lo{lv}"]), fnum(r[f"hi{lv}"])) for lv in levels],
                         r["reading"]]))
    body += [r"\bottomrule", r"\end{tabular}"]
    caption = (
        f"Identification of the active coordinates by cell and prior family, scored at each run's "
        f"last readout. Upper block: average precision of ranking the coordinates by the posterior "
        f"median of the cell's own sparsity parameter (native) and by the estimated Sobol' index, "
        f"the F1 score of the predicted active set at the analysis's activity threshold, and the "
        f"median size of that set, over the complete runs ({code(path.name)}). Lower block: each R2-D2 cell minus its half-Cauchy "
        f"twin on the same (family, seed), with the (family, seed)-cluster bootstrap percentile "
        f"interval of the median paired difference and the PR4 reading against the preregistered "
        f"equivalence band ({code(pr4_path.name)}). {CELL_NAMING} Read from {snap.scope()}."
    )
    write_table(outdir / "study_identification.tex", [f"source: {path.name}, {pr4_path.name}"],
                caption, "app:so:study:tab:identification", body)


# =================================================================================================
# 5. Diagnostics and cost by cell, with how many runs shared a GPU
# =================================================================================================


def packed_runs() -> tuple[set[tuple[str, str, int]], int, list[str]]:
    """Every run a packed work list names, as (method, family, seed); the launcher's K; the lists.

    A work list line is '<structure>/<parameterization>_r2d2 <family> <seed>'; the analysis's method
    name joins structure and parameterization with '-'. K is the launcher's default (`K="${K:-8}"`).
    """
    m = re.search(r'^K="\$\{K:-(\d+)\}"', PACKED_LAUNCHER.read_text(encoding="utf-8"), re.M)
    if m is None:
        raise SystemExit(f"regen_study_tables: no K default in {PACKED_LAUNCHER}")
    k = int(m.group(1))
    runs: set[tuple[str, str, int]] = set()
    lists = sorted(WORK_DIR.glob("*.txt"))
    for wl in lists:
        for line in wl.read_text(encoding="utf-8").splitlines():
            line = line.split("#", 1)[0].strip()
            if not line:
                continue
            cell, family, seed = line.split()
            runs.add((cell.replace("/", "-"), family, int(seed)))
    return runs, k, [p.name for p in lists]


def study_diagnostics_cost(snap: Snapshot, outdir: Path) -> None:
    diag_path = snap.tables / "diagnostics_by_method.csv"
    cost_path = snap.tables / "cost_by_method_device.csv"
    diag = {r["method"]: r for r in read_csv(diag_path)}
    cost = read_csv(cost_path)
    packed, k, lists = packed_runs()
    prior = {r["method"]: r["prior_family"] for r in read_csv(snap.regret_file)}

    # packed[(method, device)]: runs of this method that a packed work list names, by the device the
    # run was created on (inventory.csv).
    n_packed: dict[tuple[str, str], int] = {}
    for r in snap.inventory:
        if (r["method"], r["family"], int(r["seed"])) in packed:
            key = (r["method"], r["device_created"])
            n_packed[key] = n_packed.get(key, 0) + 1
    total_packed = sum(n_packed.values())
    n_r2d2 = sum(1 for r in snap.inventory if prior.get(r["method"]) == "R2D2")

    body = [r"\begin{tabular}{llrrrrrrr}", r"\toprule",
            row(["method", "prior", "iterations", hd("gate-", "excluded"), hd("max R-hat", "(median)"),
                 hd("min ESS", "(median)"), hd("divergences", "(mean)"), hd("at tree", "cap"),
                 "exceptions"]),
            r"\midrule"]
    prev_prior = None
    for m in snap.methods:
        if prev_prior is not None and prior[m] != prev_prior:
            body.append(r"\midrule")
        prev_prior = prior[m]
        r = diag[m]
        body.append(row([method_cell(m), PRIOR_NAMES[prior[m]], r["n_iter"],
                         f3(fnum(r["gate_excluded_rate"])), f3(fnum(r["r_hat_max_median"])),
                         g3(fnum(r["n_eff_min_median"])), f3(fnum(r["divergences_mean"])),
                         f3(fnum(r["frac_at_tree_cap"])), r["exception_rows"]]))
    body += [r"\bottomrule", r"\end{tabular}", r"\par\medskip",
             r"\begin{tabular}{lllrrrrrr}", r"\toprule",
             row(["method", "prior", "device", "runs", hd("runs packed", f"{k} per GPU"), hd("fit s", "(median)"),
                  hd("acquisition s", "(median)"), hd("iteration s", "(median)"),
                  hd("fit and", "acquisition", "hours")]), r"\midrule"]
    prev_method = None
    for r in cost:
        if prev_method is not None and r["method"] != prev_method and \
                prior.get(r["method"]) != prior.get(prev_method):
            body.append(r"\midrule")
        prev_method = r["method"]
        device = re.split(r"[ -]", r["device"].removeprefix("NVIDIA "))[0]  # the GPU model alone
        gpu = r["device"] != "cpu"
        body.append(row([method_cell(r["method"]), PRIOR_NAMES[prior[r["method"]]], esc(device), r["n_runs"],
                         str(n_packed.get((r["method"], r["device"]), 0)) if gpu else "---",
                         g3(fnum(r["fit_wall_s_median"])), g3(fnum(r["acq_wall_s_median"])),
                         g3(fnum(r["iter_wall_s_median"])),
                         g3(fnum(r["hours_fit_plus_acq"]))]))
    body += [r"\bottomrule", r"\end{tabular}"]
    caption = (
        f"MCMC diagnostics and cost by method. Upper block ({code(diag_path.name)}): the share of "
        f"iterations the convergence gate excluded, the per-iteration largest R-hat and smallest "
        f"effective sample size over the sampled sites (median over iterations), the mean count of "
        f"divergent transitions, the share of iterations whose NUTS trees hit the depth cap, and the "
        f"iterations whose fit raised an exception (they queried a random point instead); the reference methods fit no MCMC model. Lower block "
        f"({code(cost_path.name)}): wall-clock seconds per iteration grouped by the device that ran "
        f"the iteration, and the summed fit and acquisition hours, a lower bound on allocated "
        f"device hours; do not compare across devices. Runs packed {k} per GPU are those the "
        f"packed launcher's work lists name ({join_words([code(x) for x in lists])}, Slurm job "
        f"name {code('r2d2-packed')}): up to {k} runs share one H200 under MPS, and their wall times "
        f"are not comparable with runs that had a GPU to themselves. Of this snapshot's {n_r2d2} "
        f"R2-D2 runs, {total_packed} ran packed and {n_r2d2 - total_packed} ran one per GPU; no "
        f"half-Cauchy or reference run is on a packed list. {CELL_NAMING} Read from {snap.scope()}."
    )
    write_table(outdir / "study_diagnostics_cost.tex",
                [f"source: {diag_path.name}, {cost_path.name}, inventory.csv; packed runs from "
                 f"slurm/work/*.txt; K from slurm/r2d2_packed.sbatch"],
                caption, "app:so:study:tab:diagnostics", body, sep="2pt")


# =================================================================================================
# 6. Stage 0's calibration of the R2-D2 prior, with the G0 decision
# =================================================================================================

_CALIBRATION_POINTS = ["target", "C_untied", "C_untied_k1", "C_tied"]


def g0_decision() -> dict:
    """Form, chosen point and its (a, b, k), parsed from stage 0's REPORT.md, section "G0 decision"."""
    text = (STAGE0_DIR / "REPORT.md").read_text(encoding="utf-8")
    sec = text.split("## G0 decision", 1)[1].split("\n## ", 1)[0]
    form = re.search(r'^\| form F \| "(\w+)", the (\w+) form', sec, re.M)
    cal = re.search(r"^\| calibration C \| (\w+): a = ([0-9.]+), b = ([0-9.]+), k = ([0-9.]+);", sec, re.M)
    if form is None or cal is None:
        raise SystemExit("regen_study_tables: could not parse the G0 decision table in stage 0's REPORT.md")
    return {"form": form.group(1), "form_word": form.group(2), "point": cal.group(1),
            "a": float(cal.group(2)), "b": float(cal.group(3)), "k": float(cal.group(4))}


def study_calibration(snap: Snapshot, outdir: Path) -> None:
    path = STAGE0_DIR / "tables" / "tier_d_calibration.csv"
    rows = read_csv(path)
    by = {r["kind"]: r for r in rows if r["kind"] in _CALIBRATION_POINTS}
    g0 = g0_decision()
    chosen = by[g0["point"]]
    for key in ("a", "b", "k"):
        if float(chosen[key]) != g0[key]:
            raise SystemExit(f"regen_study_tables: {path.name} row {g0['point']} has {key} = "
                             f"{chosen[key]}, the G0 decision {g0[key]!r}")
    target = by["target"]
    mass_col = next(h for h in rows[0] if h.startswith("P_R2_below_"))
    mass_level = mass_col.removeprefix("P_R2_below_")
    dims = round(fnum(chosen["alpha"]) / fnum(chosen["k"]))
    tq = [int(float(target[q])) for q in ("q25", "q50", "q75")]
    cq = [int(float(chosen[q])) for q in ("q25", "q50", "q75")]
    body = [r"\begin{tabular}{lrrrrrrrrr}", r"\toprule",
            row(["point", "a", "b", "k", "alpha", hd("lower", "quartile"), "median", hd("upper", "quartile"),
                 "residual", hd("R2 mass", f"below {mass_level}")]), r"\midrule"]
    for name in _CALIBRATION_POINTS:
        r = by[name]
        label = code(name) + (" (chosen)" if name == g0["point"] else "")
        if name == "target":
            label = "half-Cauchy target"
        body.append(row([label, g3(fnum(r["a"])), g3(fnum(r["b"])), g3(fnum(r["k"])),
                         g3(fnum(r["alpha"])), *[str(int(float(r[q]))) for q in ("q25", "q50", "q75")],
                         r["residual"], g3(fnum(r[mass_col]))]))
    body += [r"\bottomrule", r"\end{tabular}"]
    caption = (
        f"Calibration of the R2-D2 prior at stage 0 (directory {code(STAGE0_DIR.name)}, file "
        f"{code(path.name)}; scope: the prior alone at dimension {dims}, no optimization runs; the "
        f"profile and trend rows of the file are not shown). Each point is matched to the half-Cauchy "
        f"cells' quartiles of the prior's active-coordinate count; alpha is k times the dimension, "
        f"and the residual is the larger of the two outer-quartile gaps to the target. Gate G0 chose "
        f"the {g0['form']} ({g0['form_word']}) form at {code(g0['point'])}, (a, b, k) = "
        f"({chosen['a']}, {chosen['b']}, {chosen['k']}): its quartiles {cq[0]}/{cq[1]}/{cq[2]} "
        f"against the target's {tq[0]}/{tq[1]}/{tq[2]}, residuals {abs(cq[0] - tq[0])} and "
        f"{abs(cq[2] - tq[2])} on the lower and upper quartile (continuous "
        f"{g3(fnum(chosen['residual_c']))}). The study tables beside this one were read from "
        f"snapshot {code(snap.name)}."
    )
    write_table(outdir / "study_calibration.tex", [f"source: {STAGE0_DIR.name}/tables/{path.name}, "
                                                    f"{STAGE0_DIR.name}/REPORT.md section G0 decision"],
                caption, "app:so:study:tab:calibration", body)


# =================================================================================================
# Registry, generation, --check
# =================================================================================================

TABLE_REGISTRY = [
    ("study_final_regret.tex", study_final_regret),
    ("study_effects.tex", study_effects),
    ("study_twins.tex", study_twins),
    ("study_identification.tex", study_identification),
    ("study_diagnostics_cost.tex", study_diagnostics_cost),
    ("study_calibration.tex", study_calibration),
]


def generate_all(snap: Snapshot, outdir: Path) -> None:
    outdir.mkdir(parents=True, exist_ok=True)
    for filename, fn in TABLE_REGISTRY:
        fn(snap, outdir)
    print(f"regen_study_tables: {len(TABLE_REGISTRY)} table(s) from snapshot {snap.name} written to {outdir}")


def run_check(snap: Snapshot, tables_dir: Path) -> int:
    with tempfile.TemporaryDirectory(prefix="study_tables_check_") as tmp:
        fresh_dir = Path(tmp)
        generate_all(snap, fresh_dir)
        mismatches = []
        for name, _fn in TABLE_REGISTRY:
            committed, fresh = tables_dir / name, fresh_dir / name
            a = committed.read_text(encoding="utf-8").splitlines(keepends=True) if committed.exists() else []
            b = fresh.read_text(encoding="utf-8").splitlines(keepends=True)
            d = list(difflib.unified_diff(a, b, fromfile=str(committed), tofile=str(fresh)))
            if d:
                mismatches.append((name, d))
    if mismatches:
        for name, d in mismatches:
            print(f"=== {name} differs ===")
            sys.stdout.writelines(d)
        print(f"regen_study_tables --check: {len(mismatches)} of {len(TABLE_REGISTRY)} table(s) differ: "
              + ", ".join(name for name, _ in mismatches))
        return 1
    print(f"regen_study_tables --check: {len(TABLE_REGISTRY)} tables current")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="regenerate into a temp dir and diff")
    parser.add_argument("--snapshot", type=Path, default=DEFAULT_SNAPSHOT,
                        help="analysis snapshot directory (default: sagp_analysis/r2d2/latest)")
    parser.add_argument("--tables-dir", type=Path, default=TABLES_DIR,
                        help="where the fragments are written, or diffed against with --check "
                             "(default: docs/thesis/tables)")
    args = parser.parse_args(argv)
    snap = Snapshot(args.snapshot)
    if args.check:
        return run_check(snap, args.tables_dir)
    generate_all(snap, args.tables_dir)
    return 0


if __name__ == "__main__":
    sys.exit(main())
