"""Tests of `docs/thesis/regen_study_tables.py`, the generator of the R2-D2 study's thesis tables.

Every test runs the generator on the committed G3 (pilot) snapshot, `sagp_analysis/r2d2/
2026-09-29-0245/`, into a temporary directory: the committed thesis tables are never written. The
generator reads only CSV and text files, so the whole module runs in about a second.
"""
import re
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
THESIS_DIR = REPO_ROOT / "docs" / "thesis"
SCRIPT = THESIS_DIR / "regen_study_tables.py"
G3_SNAPSHOT = REPO_ROOT / "sagp_analysis" / "r2d2" / "2026-09-29-0245"

EXPECTED = [
    "study_final_regret.tex",
    "study_effects.tex",
    "study_twins.tex",
    "study_identification.tex",
    "study_diagnostics_cost.tex",
    "study_calibration.tex",
]


def run(*args: str) -> subprocess.CompletedProcess:
    return subprocess.run([sys.executable, str(SCRIPT), *args], cwd=str(THESIS_DIR),
                          capture_output=True, text=True)


@pytest.fixture(scope="module")
def tables(tmp_path_factory) -> Path:
    out = tmp_path_factory.mktemp("study_tables")
    result = run("--snapshot", str(G3_SNAPSHOT), "--tables-dir", str(out))
    assert result.returncode == 0, result.stdout + result.stderr
    return out


def caption(path: Path) -> str:
    m = re.search(r"^\\caption\{(.*)\}\\label\{", path.read_text(encoding="utf-8"), re.M)
    assert m, f"{path.name}: no \\caption line"
    return m.group(1)


def test_the_six_fragments_are_written_and_non_empty(tables: Path) -> None:
    assert sorted(p.name for p in tables.iterdir()) == sorted(EXPECTED)
    for name in EXPECTED:
        text = (tables / name).read_text(encoding="utf-8")
        assert text.startswith("% generated by regen_study_tables.py -- do not edit\n")
        assert r"\begin{tabular}" in text and r"\midrule" in text, name
        assert re.search(r"\\label\{app:so:study:tab:\w+\}", text), name


def test_the_fragments_pass_the_appendix_lint(tables: Path, tmp_path: Path) -> None:
    """lint_tex.py checks every .tex beside it and under tables/: a copy holding only the lint,
    the notation package, numbers.tex and the six fragments runs every check that applies to them
    (braces and environments, labels, host-only commands, raw notation, undefined SO macros)."""
    shutil.copy(THESIS_DIR / "lint_tex.py", tmp_path)
    shutil.copy(THESIS_DIR / "synthobj-notation.sty", tmp_path)
    (tmp_path / "tables").mkdir()
    shutil.copy(THESIS_DIR / "tables" / "numbers.tex", tmp_path / "tables")
    for name in EXPECTED:
        shutil.copy(tables / name, tmp_path / "tables")
    result = subprocess.run([sys.executable, "lint_tex.py"], cwd=str(tmp_path),
                            capture_output=True, text=True)
    assert result.returncode == 0, result.stdout + result.stderr


def test_every_caption_names_the_snapshot_and_its_scope(tables: Path) -> None:
    for name in EXPECTED:
        cap = caption(tables / name)
        assert r"\SOcode{2026-09-29-0245}" in cap, name
        if name != "study_calibration.tex":
            assert r"\SOcode{aligned10} and \SOcode{decoupled}" in cap, name
            assert "seeds 0--4" in cap, name
            assert "110 of 110 runs complete" in cap, name
    cal = caption(tables / "study_calibration.tex")
    assert r"\SOcode{2026-09-25-r2d2-prior}" in cal


def test_no_fragment_calls_the_seed_average_pooled(tables: Path) -> None:
    """Thesis wording rule: the statistic that averages over seeds is "seed-averaged"; the word
    "pooled" may appear only in a % comment that names a source file."""
    for name in EXPECTED:
        for line in (tables / name).read_text(encoding="utf-8").splitlines():
            if not line.startswith("%"):
                assert "pooled" not in line, f"{name}: {line}"


def test_the_cost_caption_counts_the_runs_that_shared_a_gpu(tables: Path) -> None:
    """The pilot's first 18 R2-D2 runs had a GPU each; the other 22 ran packed, eight per H200."""
    cap = caption(tables / "study_diagnostics_cost.tex")
    assert "Of this snapshot's 40 R2-D2 runs, 22 ran packed and 18 ran one per GPU" in cap
    assert r"\SOcode{r2d2-packed}" in cap and "MPS" in cap


def test_the_calibration_caption_carries_the_g0_decision(tables: Path) -> None:
    cap = caption(tables / "study_calibration.tex")
    assert "reference (untied) form" in cap
    assert "(1.577790731256835, 0.8043916352200708, 0.49942145555129697)" in cap
    assert "quartiles 14/37/61 against the target's 17/37/64, residuals 3 and 3" in cap


def test_check_passes_on_current_tables_and_fails_after_a_one_character_edit(tables: Path, tmp_path: Path) -> None:
    copy = tmp_path / "tables"
    shutil.copytree(tables, copy)
    ok = run("--check", "--snapshot", str(G3_SNAPSHOT), "--tables-dir", str(copy))
    assert ok.returncode == 0, ok.stdout + ok.stderr
    assert "6 tables current" in ok.stdout

    target = copy / "study_effects.tex"
    text = target.read_text(encoding="utf-8")
    i = text.index("inconclusive")
    target.write_text(text[:i] + "I" + text[i + 1:], encoding="utf-8")
    bad = run("--check", "--snapshot", str(G3_SNAPSHOT), "--tables-dir", str(copy))
    assert bad.returncode != 0
    assert "study_effects.tex differs" in bad.stdout
    assert "1 of 6 table(s) differ: study_effects.tex" in bad.stdout
